name: flight_search_app
description: "A flight search app with clean architecture"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  dev: ^1.0.0
  mockito: ^5.4.6
  build_runner: ^2.5.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  intl: ^0.20.2
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  loader_overlay: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
